### ISSUE TITLE
Make fava-plugins installable via pip

### ISSUE THREAD

**Issue by aumayr** [beancount/fava-plugins#2]
It would be really helpful if it would be possible to install `fava-plugins` as a PyPI-package, so one can just include the plugins needed in the beancount file without manually downloading, setting the PYTHONPATH, etc.

**Comment by yagebu** [comment]
Right now, with just the one plugin, it doesn't make much sense yet to upload it. Once you finish the settlement-date plugin, let's make a release, ok?

**Comment by yagebu** [comment]
Done
